### ISSUE TITLE
Hide the "Public" repo badge

### ISSUE THREAD

**Issue by WEGFan** [refined-github/refined-github#4767]
### Description

Hide the "Public" repo badge in profile page, repo list and repo page. It seems like it's recently added to GitHub but I think it's a little distractive and I prefer old behaviour, which is only shows private and archived badge.

### Screenshot

- [Profile page](https://github.com/sindresorhus)
![](https://user-images.githubusercontent.com/7558201/132538931-36e9627a-f5c9-473a-9dd1-4f07c74db17c.png)
- [Repo list](https://github.com/sindresorhus?tab=repositories&type=source)
![](https://user-images.githubusercontent.com/7558201/132539068-48994c2a-08f8-47e4-ae0e-635e01c19740.png)
- [Repo page](https://github.com/sindresorhus/refined-github)
![](https://user-images.githubusercontent.com/7558201/132538965-b90583ee-abcc-441d-b949-7b4582cd49f2.png)

### Example URL

- Profile page: https://github.com/sindresorhus
- Repo list: https://github.com/sindresorhus?tab=repositories&type=source
- Repo page: https://github.com/sindresorhus/refined-github

**Comment by kidonng** [comment]
```css
[itemprop='name'] + .Label,
.public [itemprop^='name'] + .Label,
.pinned-item-list-item-content .Label {
  display: none;
}

.rgh-ci-link .Label + .commit-build-statuses {
	margin-left: 0;
}
```
