### ISSUE TITLE
Maybe remove `monospace-textareas`?

### ISSUE THREAD

**Issue by aheckler** [refined-github/refined-github#4917]
### Description

GitHub has added a setting that does this:

https://github.blog/changelog/2021-10-12-fixed-width-font-support-in-markdown-enabled-fields/

### Example URL

Anywhere textareas are shown

**Comment by fregante** [comment]
The only thing we need to double-check, as usual, is whether this applies to every part where Refined GitHub applies. There are a lot of textareas on GitHub, even in options/settings pages.

**Comment by fregante** [comment]
<img width="279" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/140643079-3b844c43-69d9-4176-b0ee-1791443a48fb.png">

Should we restore it? 😒

**Comment by fregante** [comment]
I add a CSS hotfix for now

**Comment by cheap-glitch** [comment]
It's still working for me. Maybe your settings got reset?

**Comment by fregante** [comment]
It's working because I added a hotfix. Disable RGH

**Comment by cheap-glitch** [comment]
![screenshot-1636292208](https://user-images.githubusercontent.com/46634000/140647340-43a4cc52-3b72-47d8-bc8d-9d31483d3eb8.png)

**Comment by fregante** [comment]
Ahhhh I didn't even realize it's an option. Why make it an option? :(

**Comment by giladarnold** [comment]
Will you consider restoring this feature (disabled by default) for the helpless Github Enterprise users?

**Comment by busches** [comment]
> Will you consider restoring this feature (disabled by default) for the helpless Github Enterprise users?

As I fellow GHE user, I understand where you're coming from.  You can paste in the removed css into the options until GHE is updated. We won't add an option disabled for everyone and do consider GHE when removing features like this, but this is super easy to get back.

**Comment by cheap-glitch** [comment]
>  You can paste in the removed css into the options

It's basically just this :point_down: 
```css
textarea {
	font-family: ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace !important;
}
```

(and maybe the font size should be adjusted too).

**Comment by WEGFan** [comment]
It seems that github didn't add monospace to the create new release page
![](https://user-images.githubusercontent.com/7558201/143690687-294a613a-690a-47ce-ab38-d8cfb32f477c.png)

**Comment by cheap-glitch** [comment]
> It seems that github didn't add monospace to the create new release page

This can be (hot)fixed with:

```css
#release_body {
	font-family: ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace !important;
}
```
