### ISSUE TITLE
Missing green new button

### ISSUE THREAD

**Issue by haoadoresorange** [refined-github/refined-github#5137]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

Whenever I turn on the extension the green button on the left on homepage is gone

- here's extension disable
![image](https://user-images.githubusercontent.com/22086462/144273211-94cda8b5-c595-4d95-ac06-7f85e83d4fd2.png)
- here's extension enable
![image](https://user-images.githubusercontent.com/22086462/144273350-551180e0-c938-434e-847a-78bb1dfebb07.png)

`Find features` doesn't find it. I manually disable all features showed in the console but doesn't resolve it either.

### Example URL

https://github.com

### Browser(s) used

Firefox

**Comment by fregante** [comment]
It's a "cleanup" feature. The same button is available on the top right menu, on every page (not just the homepage)

<img width="573" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/144277585-f1dd4b1e-ba05-4d9f-a835-10e3a72f5246.png">

**Comment by haoadoresorange** [comment]
I understand that, is it possible to keep the button ? I know there that same button but I use the green one quite often.

**Comment by yakov116** [comment]
Use the custom CSS box 

```css
.rgh-clean-dashboard .dashboard-sidebar a[href='/new'] {
	display: block !important;
}
```

**Comment by jerone** [comment]
Improved version of above custom CSS:

```css
/* https://github.com/refined-github/refined-github/issues/5137#issuecomment-984060503 */
.dashboard-sidebar a.btn[href$="/new"] {
	display: block !important;
}
```

**Comment by aidan-gibson** [comment]
Neither of those worked for me; the following did:
```css
.dashboard-sidebar a.Button[href='/new'] {
    display: inline-block !important;
}
```

**Comment by aidan-gibson** [comment]
Above solution clips the button, I used the following to avoid clipping, with the understanding that it probably breaks scrolling or something:
```css
.dashboard-sidebar .loading-context {
    min-height: auto !important;
}
.dashboard-sidebar a.Button[href='/new'] {
    display: block !important;
}
```
