### ISSUE TITLE
Make "repo code of conduct hiding" optional

### ISSUE THREAD

**Issue by tomkerkhove** [refined-github/refined-github#5270]
### Description

Make "repo code of conduct hiding" optional given this is crucial information for community building.

### Screenshot

With GitHub Refined:
![image](https://user-images.githubusercontent.com/4345663/148562693-0fca5333-9691-465a-8ea7-7be24583feaf.png)

Without GitHub Refined:
![image](https://user-images.githubusercontent.com/4345663/148562749-bfe5651f-6c43-46f6-8f7c-2b86586c8c17.png)

### Example URL

https://github.com/kedacore/keda

**Comment by tomkerkhove** [comment]
Unless this is because of a bug? I'm a bit surprised that this is hidden.

**Comment by kidonng** [comment]
Reason why it's been hidden: https://github.com/refined-github/refined-github/pull/5098#issuecomment-974897441

**Comment by tomkerkhove** [comment]
Makes sense. Can I override this myself, somehow?

**Comment by kidonng** [comment]
Sure, override [these styles](https://github.com/refined-github/refined-github/blob/e22b079d222983d84729ca230ee1350ccd4f1e0b/source/features/clean-repo-sidebar.css#L16-L22) with:

```css
.rgh-clean-repo-sidebar .Layout-sidebar .Link--muted:is(
[href$='/code-of-conduct.md' i],
[href$='/code_of_conduct.md' i]
) {
	display: inline !important;
}
```
