### ISSUE TITLE
Issue titles in issues tab are dimmed / gray

### ISSUE THREAD

**Issue by makeworld-the-better-one** [refined-github/refined-github#5299]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://github.com/makeworld-the-better-one/amfora/issues

### Browser(s) used

Firefox

### Description

Issue titles are grayed out, only in the issues tab:

![image](https://user-images.githubusercontent.com/25111343/149390274-c8fdd7a0-b91d-4551-b5dd-60a7f40620b7.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by yakov116** [comment]
Its a feature
https://github.com/refined-github/refined-github/pull/5258

To undo put the following in custom CSS box
```css
.js-issue-row .h4.h4:visited:not(:hover) {
	color: var(--color-fg-default) !important;
}
```
