### ISSUE TITLE
Consider add Refined GitHub Version in issue template

### ISSUE THREAD

**Issue by Dentrax** [refined-github/refined-github#5307]
### Description

It had better to add `Refined GitHub` version in the Issue Template.

```yaml
- type: input
    attributes:
      label: Refined GitHub Version
    validations:
      required: true
```

### Example URL

https://raw.githubusercontent.com/refined-github/refined-github/main/.github/ISSUE_TEMPLATE/1_bug_report.yml
