### ISSUE TITLE
Fix repo title wrapping on small screens

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5398]
### Description

No words honestly. We reject features and drop content from the header to avoid this stuff and they keep adding buttons. Let's limit the buttons to 50% of the screen and then have them wrap

### Screenshot

<img width="753" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/153582461-f9ff29b4-e08d-4ba4-8555-cd8fe2dc5447.png">

### Example URL

https://github.com/refined-github/refined-github

**Comment by cheap-glitch** [comment]
While we're at it, how about hiding the "Unpin" button as well?

It's not like it's a frequent operation, plus it's more convenient to manage the pins from the profile page anyway.

**Comment by kidonng** [comment]
Hipster mode:

```css
.pagehead-actions :is(
    details:not(.js-user-list-menu) summary,
    form > .btn
):not(:hover) {
    font-size: 0px;
    display: flex;
    align-items: center;
}

.pagehead-actions :is(
    details:not(.js-user-list-menu) summary,
    form > .btn
):not(:hover) svg {
    margin-right: 0 !important;
}

notifications-list-subscription-form summary:not(:hover) {
    line-height: 0 !important;
    height: 28px;
}
```

https://user-images.githubusercontent.com/44045911/153724767-a665f546-eba7-41f2-8bc0-52b107c3fb99.mov

**Comment by kidonng** [comment]
We can also hide the "Star"/"Starred" text:

- The icon shows its state clearly
- We don't hide star count so the button's click target won't become too small (as shown in the  video above)

**Comment by cheap-glitch** [comment]
I'm starting to think we might need a new `clean-repo-header` feature :smile:

**Comment by kidonng** [comment]
> I like it but last time I proposed doing the same for the repo tabs it was shot down.

That's a joke inspired by your comment on https://github.com/refined-github/refined-github/issues/4286#issuecomment-831005339

**Comment by fregante** [comment]
50% of the feature:

```css
.pagehead-actions {
	flex-shrink: 3 !important;
}
```

Missing:

- [ ] add `margin-bottom` to the buttons so that they're spaced out correctly

<img width="595" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/167059138-1050436a-06de-4d84-9831-823462c670d8.png">
