### ISSUE TITLE
"How can I undo unwanted styles?"

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5501]
> How can I undo unwanted styles?

### Feature styles

Some styles are associated with a certain feature. Disabling the feature would prevent the styles from applying.

Examples:

- Dimmed issue/pull request title: `dim-visited-conversations`
- Label next to the repository name in the header: `hide-repo-badges`
- Commits, forks and new followers on dashboard: `hide-noisy-newsfeed-events`

### Decorative styles

[Some styles](https://github.com/refined-github/refined-github/blob/37dc0c1f6c9ff7acc08781d48abbcceb52fb06b9/source/refined-github.ts#L3-L24) are purely decorative and thus cannot be disabled directly. Use the **Custom CSS** field in extension options page to undo them.

Here is a list of reverts that might be useful:

- Avatar left to the commit form: [`clean-commit-form`](https://github.com/refined-github/refined-github/pull/5350#issuecomment-1033719565)
- Watch and fork count in the repository header: [`hide-watch-and-fork-count`](https://github.com/refined-github/refined-github/issues/5406#issuecomment-1037658049)
- "New" button on dashboard: [`clean-dashboard`](https://github.com/refined-github/refined-github/issues/5137#issuecomment-984060503)
- Centered repository header: [`align-repository-header`](https://github.com/refined-github/refined-github/issues/3785#issuecomment-739625313)

<details>
<summary>Draft pull request icon (<code>emphasize-draft-pr-label</code>)</summary>

```css
@media (-webkit-min-device-pixel-ratio: 2) {
    .js-issue-row [aria-label='Open draft pull request'] svg {
        stroke: none;
        color: var(--color-fg-muted) !important;
    }
}
```

</details>
