### ISSUE TITLE
`scrollable-code-and-blockquote` mistakenly removes code block padding

### ISSUE THREAD

**Issue by hyrious** [refined-github/refined-github#5540]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/sveltejs/language-tools/issues/1418

(just find some issue with no-highlight pre elements)

### Extension version

22.3.18

### Browser(s) used

Chrome 99.0.4844.74 (x86_64) on MacOS 12.3

### Description

Just look at the code block in that issue, the padding-bottom was shorten

<img width="215" alt="Snipaste_2022-03-22_14-11-34" src="https://user-images.githubusercontent.com/8097890/159418890-d6359c41-756a-45f8-8eac-b1fb79ea7c6c.png">

because scrollable-code-and-blockquote defined&hellip;

```css
:root .comment-body :is(blockquote, pre) { padding-bottom: 0.2em }
```

&hellip;which is more specific than GitHub's

```css
.markdown-body pre { padding: 16px }
```

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any
