### ISSUE TITLE
`quick-comment-edit` is misaligned

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5558]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/sindresorhus/serialize-error/pull/69

### Extension version

22.2.13

### Browser(s) used

Safari 15.4

### Description

I'm still on an old version so I'm not sure if it has been fixed in the meanwhile, but I doubt it since it appeared today.

<img width="124" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/161371071-4c9f3b89-5483-427f-8529-36c744bfa4c1.png">

Strangely it's broken in the example PR, but not in the current issue:
<img width="187" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/161371120-88bb7580-3487-4da8-bd40-93eea093dfe6.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by cheap-glitch** [comment]
Can be hotfixed with something like:

```css
.timeline-comment-actions > div:first-child {
	display: flex !important;
	flex-direction: row-reverse;
}

.rgh-quick-comment-edit-button {
	padding: 0 4px !important;
}
```

![image](https://user-images.githubusercontent.com/46634000/161385298-298925c3-2cad-4064-854a-44e972d919a9.png)
