### ISSUE TITLE
No-text repo tabs on mobile

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5805]
We discussed this before but there was never a specific issue, I think.

Can we hide the labels **on mobile**?

<img width="721" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/178054009-933af74a-4a80-4fd3-ad09-60c139c723fe.png">

```css
@media (max-width:767px) {
	.UnderlineNav-item [data-content] {
		overflow: hidden;
		display: inline-block;
		width: 0; /* Preserve the button height; display: none collapses it*/
	}
	.UnderlineNav-item svg {
		margin-right: 0 !important;
	}
}
```

If the tabs aren't differentiable enough, we can keep the hover state on:

<img width="721" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/178053995-8e8d850a-3d83-4e9d-ae6a-28004d0f29f8.png">

But there's probably a better style for that.

```css
.UnderlineNav-item {
	background: var(--color-action-list-item-default-hover-bg);
}
```

**Comment by fregante** [comment]
Related:

- https://github.com/refined-github/refined-github/issues/5398#issuecomment-1037399880
- https://github.com/refined-github/refined-github/issues/4286#issuecomment-831005339

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/4836

**Comment by fregante** [comment]
![before](https://user-images.githubusercontent.com/1402241/178056966-6b6fce77-cd8c-48d9-8d16-64ffc7c30f98.gif)

**Comment by fregante** [comment]
Updated CSS

```css

@media (max-width:767px) {
	.UnderlineNav-item:not(.selected):not(:hover, :focus) {
		background: var(--color-canvas-default);
	}
	.UnderlineNav-item:not(.selected) [data-content] {
		overflow: hidden;
		display: inline-block;
		width: 0; /* Preserve the button height; display: none collapses it*/
	}
	.UnderlineNav-item:not(.selected) svg {
		margin-right: 0 !important;
	}
	.UnderlineNav-item:not(.selected) .Counter {
		background: none;
	}
}
```

## Demo (8 tabs visible)


<img width="602" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/234822191-503a1d26-a1f3-4828-b846-4899b0e55883.png">

## Native (4 tabs visible)

<img width="602" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1402241/234822171-1ecccc57-f0a3-4a02-8861-98b363f7a7d2.png">
