### ISSUE TITLE
Hide successful checks by default in PRs

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5856]
### Description

Currently PRs look like this, which makes it difficult to see what failed exactly:

<img width="810" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/181167879-6bdd16f8-66b0-433d-abe4-f8e7e97ad472.png">

What if we hid the passing ones _if any are failing?_

<img width="811" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/181168120-a037b7bc-5fe2-44ea-8562-9276d8e740ba.png">

### Drawbacks

- In this mode, you can't see which tests actually succeeded
- Modifying this active widget could be difficult, but maybe a smart use of `element-observer` could make it easy enough
- This feature could be implemented in CSS only with `:has`, but then it would be difficult to "show all" (maybe via `:not(:focus-within)`?)

### Similar requests

- https://github.com/refined-github/refined-github/issues/5855
- https://github.com/refined-github/refined-github/issues/5621
- https://github.com/refined-github/refined-github/issues/5062
- https://github.com/refined-github/refined-github/issues/4958
- https://github.com/refined-github/refined-github/issues/3136

### Example URLs

https://github.com/fregante/content-scripts-register-polyfill/pull/58

**Comment by fregante** [comment]
cc @janpio @staabm @kidonng opening this issue to propose the smallest possible solution to this issue: hiding successful checks. No filters, no sorting, no toggles. Just hide them + maybe offer a way to see the rest (which are still available on the Actions tab)

**Comment by staabm** [comment]
Maybe it would make sense to turn the "xx errored", "yy succeeded" or "zz skipped" status text into filter links.

Like click on "xx succeeded" will filter the list on the succesed ones etc?

**Comment by kidonng** [comment]
> * In this mode, you can't see which tests actually succeeded

Em, isn't that what we want? As I often said, we can experiment and if people don't like it, we can always hotfix disabling it.

**Comment by fregante** [comment]
Here's a CSS-only feature with `:has()`:

```css
/* Hide successful statuses only if any failed */
.merge-status-list:has(.octicon-x) .merge-status-item:has(.octicon-check) {
	display: none !important;
}
```

<img width="924" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/181171403-a5ecdaec-b148-475e-8cb9-cc2a8dcf4acf.png">


And here's another version that probably solves every single problem at once (except "sort by name")

```css
/* Dim successful checks and bring failed checks to the top (unless everything is successful) */
.merge-status-list:has(.octicon-x) .merge-status-item:has(.octicon-check) {
	opacity: 0.5;
	order: 1
}

.merge-status-list:has(.octicon-x) {
	display: flex;
	flex-direction: column;
}
```

<img width="911" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/181171839-e6fc7fa2-f7d1-42d1-aa70-5089e73191f8.png">


I don't particularly care that this is "Safari-only" at the moment because Chrome will follow soon and Firefox will follow eventually. Feels like a good win for 8 lines of inert code 😃
