### ISSUE TITLE
Set up automated live testing of some CSS selectors

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6060]
_Originally posted in https://github.com/refined-github/refined-github/issues/6023#issuecomment-1270439879_
      
---

> > set up some sort of automated live testing of CSS selectors
> 
> Should not be too difficult, cant make a selector check on load of the feature?

1. Given the complex logic, we need to test the whole selector for the tests to be useful
2. Testing the selectors "live" means we have to import them into the JS side and run them at some point
3. Given the complex logic, these selectors will not appear on every page, so we can't actually _assert_ that a selector _must_ match an element on any given page the user loads.

The proper testing harness I'm thinking of would look like:

1. In node
1. Loads `no-unnecessary-split-diff-view.css`
2. Extracts the selectors and any related URLs, to be defined like:
	```css
	/** @expect-on http://github.com/some/dead-repo*/
	.repo-bar .tab:has(.counter[label=0]) {
		display:none;
	}
	```
4. Fetches the URL and looks for the selector on the page
