### ISSUE TITLE
Show avatar next to username in conversations (mobile)

### ISSUE THREAD

**Issue by kyoyacchi** [refined-github/refined-github#6239]
### Description

Can you add avatar next to username's, it's removed in Github's mobile version recently.. 

### Screenshot

![Screenshot_20230121-175244](https://user-images.githubusercontent.com/63583961/213872422-b0dc62f9-29a0-4507-ac54-689a448c2783.jpg)

This is how it looks currently.
### Example URLs

https://github.com/refined-github/refined-github/issues/1

**Comment by kidonng** [comment]
That blank space is some wasted real estate. Made a partially working version:

```css
@media (max-width: 767px) {
    .TimelineItem-avatar {
        display: block !important;
        left: -6px;
        top: 6px;
    }

    .TimelineItem-avatar .avatar {
        width: 16px;
        height: 16px;
    }

    .timeline-comment-header .author {
        margin-left: 16px;
    }

    button.rgh-quick-mention {
        display: none;
    }
}
```

<img width="419" alt="image" src="https://user-images.githubusercontent.com/44045911/232127146-38b50d70-1352-4040-8523-3dc41d98670b.png">

This only works for the first comment (initial post), others has wrong position. I'm putting it off a bit

@fregante are you interested?
