### ISSUE TITLE
`file-age-color` set base color

### ISSUE THREAD

**Issue by Shinigami92** [refined-github/refined-github#6369]
### Description

I really like the new `file-age-color` feature but it would be nice to apply a base color like green or blue easily

Currently I need to try out and hack some colors for every single value like so:
```css
:root [data-rgh-heat="1"] {
    color: hsl(75deg 100% 38%) !important;
}
:root [data-rgh-heat="2"] {
    color: hsl(75deg 69% 40%) !important;
}
:root [data-rgh-heat="3"] {
    color: hsl(75deg 57% 41%) !important;
}
:root [data-rgh-heat="4"] {
    color: hsl(75deg 47% 41%) !important;
}
:root [data-rgh-heat="5"] {
    color: hsl(75deg 36% 42%) !important
}
:root [data-rgh-heat="6"] {
    color: hsl(75deg 26% 43%) !important
}
:root [data-rgh-heat="8"] {
    color: hsl(75deg 6% 44%) !important;
}
```

It is nice to have it customization like this, but it would also be nice to select just:
red, green, blue or yellow
or maybe just a hue slider? I don't know what's possible

### Screenshot

<img src="https://user-images.githubusercontent.com/7195563/220198609-ad7f581f-8aa1-4e38-85ff-06dd0302dd03.png" width="150px" />

### Example URLs

https://github.com/refined-github/refined-github
