### ISSUE TITLE
Expand all dashboard items by default

### ISSUE THREAD

**Issue by jahirfiquitiva** [refined-github/refined-github#6416]
### Description

GitHub collapses some events in the Feed, like Starred repositories.

I would like to have an option so that all those items are *expanded* by default, just so I don't miss a thing in there.

Here's what I'm referring to

**Collapsed:**
![Shot 2023-03-14 at 11 55 34@2x](https://user-images.githubusercontent.com/10360816/225080920-0ef71283-e81c-4bb3-baeb-e7993d539c89.png)

**Expanded:**
![Shot 2023-03-14 at 11 55 23@2x](https://user-images.githubusercontent.com/10360816/225080985-9c29b63d-99e2-40e0-bada-55bd7002cb6f.png)

### Example URLs

https://github.com

**Comment by fregante** [comment]
- https://github.com/refined-github/refined-github/pull/6191

Refined GitHub actually did this in the past but it was part of a feature that was fickle. That feature was dropped with a wish to reintroduce some improvements like this one.

PR welcome

**Comment by fregante** [comment]
It would also be nice to collapse their margins a bit: (without messing with borders, background, etc, which was the demise of the previous feature)

<img width="612" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1402241/225084282-f958f451-f0ce-4a38-9f4d-4e0826612c94.png">

**Comment by jahirfiquitiva** [comment]
@fregante I'm not sure how to build the feature and create the PR.

But, if it's any helpful... I got the desired look by using this css:


```css
div.body > div.Details.open .Details-content--hidden .js-feed-item-view .Box {
  margin-top: calc(var(--primer-borderWidth-thin, 1px) * -1) !important;
}

div.body > div.Details.open .js-feed-item-view:first-of-type .Box,
div.body > div.Details.open .Details-content--hidden .js-feed-item-view:not(:last-of-type) .Box {
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

div.body > div.Details.open .Details-content--hidden .js-feed-item-view .Box {
  border-top-right-radius: 0;
  border-top-left-radius: 0;
}
```

Now if the div with class `Details` within the div with class `body`, has the classes `open Details--on`, that's enough to show those items expanded

<img width="381" alt="Shot 2023-03-14 at 13 01 06@2x" src="https://user-images.githubusercontent.com/10360816/225096511-43d66d52-5bd7-4673-b791-76ac2599b1c8.png">
