### ISSUE TITLE
Alternate version of `clean-rich-text-editor`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6512]
Some items in text editor toolbar can be toggled on mobile:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/44045911/231987204-9f4bb963-50d8-4400-b172-abf213cd871f.png">

I'm thinking about bringing this to desktop instead of hiding them:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/44045911/231991697-87473ab8-3f54-4d78-a101-6ff00e3eb2de.png">

(This screenshot is with Refined GitHub turned off)

This is not fully equivalent to current `clean-rich-text-editor` (only 3 hidden items overlap), but it does hide the same amount of noise (hide 5 items -> replace 6 items with 1 toggle).

```css
    @media (min-width: 768px) {
        markdown-toolbar > .d-none.d-md-inline-block {
            display: none !important;
        }

        markdown-toolbar > .d-block.d-md-none {
            display: inline-block !important;
        }
    }
    
    @media (min-width: 1012px) {
        markdown-toolbar.Details--on > .Details-content--hidden {
            position: absolute;
            top: 48px;
            width: auto !important;
            z-index: 10;
            background-color: var(--color-canvas-default);
            border: 1px solid var(--color-border-default);
            border-radius: 6px;
        }
        
        markdown-toolbar [aria-label="Toggle text tools"] {
            padding: 4px !important;
        }
    }
```
