### ISSUE TITLE
`readable-title-change-events` causes overflow with unwrappable PR titles

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6548]
### Description

This doesn't really appear in the wild, buuuuuuut it's also easy to fix (enable word-break the modern way (I don't know which property that is)).

## Native

<img width="945" alt="Screenshot 4" src="https://user-images.githubusercontent.com/1402241/233592281-c1a1f450-efa2-4fff-912c-4e62344810dd.png">

## Refined GitHub 

<img width="945" alt="Screenshot 5" src="https://user-images.githubusercontent.com/1402241/233592292-666c58e9-cf40-437a-a942-ca208d1e6cf8.png">

### How to replicate the issue + URL

https://github.com/refined-github/sandbox/pull/62

### Extension version

23.4.15

### Browser(s) used

Chrome

**Comment by 134130** [comment]
Github's css class for word-break is this 
```css
.wb-break-word {
    word-break: break-word !important;
    word-wrap: break-word !important;
    overflow-wrap: break-word !important;
}
```
Get element which uses this class with this on https://github.com/refined-github/refined-github/issues/6548 page (issue page)
```js
document.querySelector('h1.gh-header-title')
```
