### ISSUE TITLE
Custom CSS is broken in New Code View feature

### ISSUE THREAD

**Issue by OmkarK45** [refined-github/refined-github#6588]
### Description

- New code view feature preview from github, when enabled, breaks the custom CSS injected by Refined-github. 
- Here's the before and after:

#### Before [Custom Font loaded via Refined-github Custom css option, New Code View feature Disabled]
![image](https://user-images.githubusercontent.com/45557594/234979869-78492dd6-0d34-4e90-b780-b5837e4bcc0a.png)

#### After [Custom Font loaded via Refined-github Custom css option, New Code View feature Enabled]
![image](https://user-images.githubusercontent.com/45557594/234980142-9640c6b3-b7cf-4f3d-8b47-e4c5fa16de9f.png)

It seems like Github is rendering the code in a `<textarea />` tag

Expected behavior: The custom CSS related to code pane should reflect properly. 

### How to replicate the issue + URL

To replicate, please turn on the new Github Code View feature from here: 
1. Click on your profile avatar
2. On the dropdown, choose Feature Preview
3. Enable Code View feature
4. Reload
![image](https://user-images.githubusercontent.com/45557594/234980427-02b85b93-a844-4267-8cad-6e4e6219f1c0.png)

Inject this into custom CSS option of refined-github extension

```css

pre, code, .blob-code, .blob-code-marker {
  font-family: 'JetBrains Mono', monospace !important;
	font-size: 16px !important;
}

.commit-ref, .head-ref{

font-family:  'JetBrains Mono', monospace !important;
font-size: 14px !important;
}

```

URL : https://github.com/tailwindlabs/tailwindcss/blob/master/src/index.js

### Extension version

23.4.26

### Browser(s) used

Google Chrome 112.0.5615.138 (Official Build) (64-bit) (cohort: Stable)

**Comment by fregante** [comment]
This is unrelated to Refined GitHub. The CSS is obviously being injected, it’s just that the markup changed so you also need to change your CSS

**Comment by fregante** [comment]
Some context for your specific issue:

- https://github.com/refined-github/refined-github/issues/6477#issuecomment-1501066017
- https://github.com/refined-github/refined-github/issues/6336#issuecomment-1498645639

**Comment by Paciupa** [comment]
@zoj613, you can just add `.react-code-text` class in your selector like this:
```css
pre, code, .blob-code, .blob-code-marker, .react-code-text {
	font-family: 'Iosevka Nerd Font', monospace !important;
	font-size: '16px';
}
```

**Comment by zoj613** [comment]
That worked, thanks @Paciupa

**Comment by varungbt** [comment]
that works !

**Comment by KaranAhlawat** [comment]
For anyone who comes here later on, this is what curerntly works for me so that the selections and fonts and all that line up properly

```css
pre, code, .blob-code, .blob-code-marker, .react-blob-textarea, .react-line-numbers, .react-code-text {
	font-size: .85rem !important;
}
```
