### ISSUE TITLE
Rewrite `fit-textareas` with CSS grid

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6642]
https://github.com/fregante/fit-textarea has long been "a little broken", in fact its v3 has been reverted due to Chrome performance and the feature is disabled in Safari due to v2’s performance there.

As was suggested before, maybe it's time to drop the module and make a minimal version with the recent CSS grid "hack", which frees us from any computation.

All the JS we need is probably:

```js
function wrap(textarea) {
	wrap(textarea, <div className="rgh-fit-textarea"/>)
}

function fit({delegateTarget: textarea}) {
	textarea.parentElement.dataset.text = textarea.value
}

function init() {
	observe('textarea', wrap, {signal})
	delegate(document, '.rgh-fit-textarea', 'input', fit, {signal})
}
```
and just this CSS:

```css
.rgh-fit-textarea {
	display: grid;
}
.rgh-fit-textarea:before {
	content: attr(data-text);
	grid-area: 1/1;
	whitespace: pre-wrap;
	/* some more font/padding matching to the textarea field */
}
.rgh-fit-textarea textarea {
	grid-area: 1/1;
	height: auto;
}
```

The reason to integrate this here instead of upgrading my module is:

- it's much easier to just support GitHub, we know its style is mostly consistent in this area
- I hope that this functionality will be native in 12 months so I can deprecate the package without investing more time into it: https://github.com/fregante/fit-textarea/issues/22

### Downsides

`fit-textarea`’s performance might not be perfect, but it works automatically. By hardcoding the sizing/fonts of the textarea we risk issues down the line. But I think it's worth it.
