### ISSUE TITLE
`sticky-sidebar`: conflict with the forks menu when `:active`

### ISSUE THREAD

**Issue by vintagesucks** [refined-github/refined-github#6761]
### Description

Similar to #5214, `sticky-sidebar` conflicts with the forks menu when `:active`. 

The fix from that PR does not work for the forks menu because it is missing the `js-user-list-menu` class. The following custom CSS worked for me as a fix:

```css
.rgh-sticky-sidebar-enabled .pagehead-actions .details-overlay {
	z-index: unset;
}
```

### How to replicate the issue + URL

https://github.com/refined-github/refined-github

* Open the forks menu
* Click (and hold) inside the details menu

Video:

https://github.com/refined-github/refined-github/assets/13335308/f468a630-edb3-4a4b-bb4d-317c44cd8c28

### Extension version

23.6.17

### Browser(s) used

Firefox 115.0b9 (64-Bit)
