### ISSUE TITLE
User defined CSS still doesn't overwrite refined-github.css

### ISSUE THREAD

**Issue by andersonaddo** [refined-github/refined-github#6864]
### Description

When the user specifies custom css, it looks like it still gets overwritten by the default refined-github.css. I know you've done some work on this in the past, I can see the previous tickets. But it looks  like the issue is still there in some respects.

### How to replicate the issue + URL

This is the custom css I'm trying to implement:
```css
.js-issue-row .color-fg-muted [href$="#partial-pull-merging"][aria-label*="changes"]{
	color:var(--fgColor-default, var(--color-fg-default)) !important;
}
```
(I'm essentially just redoing the color changes you did in the built in css).

Let's try it on a random repo: https://github.com/invertase/react-native-firebase/pulls

<img width="1433" alt="image" src="https://github.com/refined-github/refined-github/assets/34724755/1b4701ee-9ae2-405f-94e9-d8829104bde8">

If you look at this page with the web inspector on, you can see that my changes are still being overwritten. You can see the built in css still at the top of the render hierarchy.

### Extension version

23.8.24

### Browser(s) used

Firefox Mac 116.0.3 (64-bit)
