### ISSUE TITLE
`dim-bots`: configurable bot names via configuration

### ISSUE THREAD

**Issue by panva** [refined-github/refined-github#7016]
### Description

I would like there to be a configuration for the `dim-bots` feature so that project-specific bots may be added by users themselves.

### Example URLs

n/a

**Comment by fregante** [comment]
Refined GitHub can't have configurable features, see:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options

<img width="600" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/5a583623-34c9-4dd3-b7dc-0e6ea0baa73b">

**Comment by fregante** [comment]
The good news is that this feature can be partially written in CSS locally, using something like:

```css
/* Example selector, won't work*/
.js-issue:has(.opened-by [href*="your-fav-bot"]) {
	opacity: 0.7;
}
```
