### ISSUE TITLE
`sticky-sidebar` - Always stick and scrollable

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7147]
### Description

Followup discussion to https://github.com/refined-github/refined-github/issues/5939 opened by @janpio 

Should we make the sidebar always sticky _and scrollable_?

Currently we only make the sidebar sticky when it fits the screen, but disable it otherwise. However I realized that GitHub has a scrollable sidebar for file lists, both in PRs an in /blob/ and /tree/ views. The only (maybe major) difference is that those sidebars are stuck to the viewport border, like a true sidebar, are not floating "centered" in the viewport.

Thoughts?

### Example URLs

Here

**Comment by janpio** [comment]
For me as a contributor in a repository, the sidebar is the "configuration panel" for the whole issue and discussion. I always want to be able to see it and access all its information. Otherwise I need to scroll up any time I want to change a label or project field of the issue - which is something I do 8 hours a day.

So clear 👍 from me.

**Comment by fregante** [comment]
Let's try it. It would let us simplify the feature quite a bit. The complex part here would be detecting the notification bar.

I'm confident this feature could just be a "disableable CSS-only feature" looking like:

```css
[rgh-sticky-sidebar] {
	--notification-bar: 70px;
	--issue-bar: 60px;
	--top: var(--issue-bar);
	.sidebar {
		position: sticky;
		top: var(--top);
		max-height: calc(100vh - var(--top));
		overflow-y: auto;
	}
	&:has(.notification-bar) {
		--top: calc(var(--issue-bar) + var(--notification-bar));
	}
}
```
