### ISSUE TITLE
`fit-textareas` - Use `field-sizing` property

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7414]
### Description

Chrome 123+: https://caniuse.com/?search=field-sizing

Implementation suggestion:

- update `fit-textarea` dependency
- re-enable feature in Safari
- conditionally enabled it as a disableable CSS feature if if `field-sizing` is supported 

Example for the last point:

```css
[rgh-fit-textareas] textarea:not(#pull_request_review_body) {
  field-sizing: content;
}
```

```js
// current .ts file contents
if (is supported) {
  void features.addCssFeature(import.meta.url, [
	pageDetect.hasRichTextEditor,
  ]);
} else {
  void features.add(import.meta.url, {
	include: [
		pageDetect.hasRichTextEditor,
	],
	init,
  });
}
```

### Example URLs

Here
