### ISSUE TITLE
`mobile-tabs` bad wrapping on 1000+ counters

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7812]
### Description

This is a little difficult to fix in flexbox. If it only happens on `bugs-tab` maybe we just need `min-width`, but that’s just a last resort and not a full fix. 

![IMG_5652](https://github.com/user-attachments/assets/cf6b4480-2a55-4212-ab2b-28eaa83801e4)

### How to replicate the issue + URL

https://github.com/oven-sh/bun

### Extension version

24.8.20

### Browser(s) used

Safari

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by AbhinRustagi** [comment]
Another solution could be to reduce the font size to try and keep the icon and counter inline

**Comment by fregante** [comment]
I think you're suggesting this, and I'm not a fan of it due to the wasted space on most tabs:

<img width="561" alt="Screenshot 5" src="https://github.com/user-attachments/assets/3fd11290-5703-4119-a629-fa2dd6524d55">

**Comment by AbhinRustagi** [comment]
Not this, I'll try it and add a screenshot

**Comment by fregante** [comment]
In the meantime, Claude may have give me some CSS to properly set up my original layout with CSS Grid:

```css
.grid-container {
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: auto auto;
  gap: 10px;
  width: 100%;
  height: 200px; /* Adjust as needed */
}

.item1 {
  grid-column: 1;
  grid-row: 1;
  justify-self: end;
}

.item2 {
  grid-column: 2;
  grid-row: 1;
  justify-self: start;
}

.item3 {
  grid-column: 1 / span 2;
  grid-row: 2;
  justify-self: center;
}

/* When item2 is missing */
.grid-container:not(:has(.item2)) .item1 {
  grid-column: 1 / span 2;
  justify-self: center;
}
```

I'll give this a go.
