### ISSUE TITLE
`conventional-commits` user feedback

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7814]
If you have any feedback about this feature, please share it below.

<table>
<tr>
<th><code>conventional-commits</code> screenshot
<tr>
	<td><img src="https://github.com/user-attachments/assets/980a2d5e-13c2-4b1b-bb80-81dc94723000">
</table>

Try it on

- https://github.com/refined-github/sandbox/commits/conventional-commits/
- https://github.com/conventional-changelog/standard-version/commits

Some bugs have already been resolved in:

- https://github.com/refined-github/refined-github/pull/7816

**Comment by GauBen** [comment]
This is a fantastic new feature, thank you a lot!

Two [standard types](https://github.com/conventional-changelog/commitlint/blob/4391fb07faff17e06ac578e10ab6191c34e780ac/%40commitlint/config-conventional/src/index.ts#L29-L45) are missing: revert, style

I would also add a tooltip when hovering the type to define them for beginners, especially the less known ones (style, perf)

**Comment by eitsupi** [comment]
Great feature!
I don't know why, but one of my repositories doesn't seem to be forming comments well.
![image](https://github.com/user-attachments/assets/cd2691bf-321c-4aff-a46f-ad5489d3d7eb)
<https://github.com/eitsupi/neo-r-polars/commits/main/>

**Comment by cooljeanius** [comment]
I think linking to the spec in more places where it's mentioned would be helpful for teaching people what exactly it does: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by fregante** [comment]
@cooljeanius where would you place that?

> one of my repositories doesn't seem to be forming comments well

Fixed. It was unable to match a regex with trailing space because the code trimmed whitespace (the node content appeared as `"feat:"` so it did not match the required `<keyword><colon><space>` format)

**Comment by cooljeanius** [comment]
> @cooljeanius where would you place that?

Well, in the release notes, for one, and wherever else it's documented...

**Comment by Andrew6rant** [comment]
I really like this new feature!

Would it be at all possible to inject the `--label-r`, `--label-g`, `--label-b`, etc. CSS rules into the entire commit listitem with the label, instead of just the label?

This would make it simpler for people to modify the CSS of commit messages based on label. For example:

![eitsupi/neo-r-polars@main (commits) with padding, border color, and margin modifed based on label message](https://github.com/user-attachments/assets/f8da4658-c295-4e43-9121-8ef78c8e71f4)

Also related to CSS, is there a particular reason the class selectors were changed to attribute selectors? (https://github.com/refined-github/refined-github/pull/7813/files#diff-3f9fea8670b02008b0c4d40fe195ad424c63509606fbe062497167784811a416)
I was under the impression that it was worse for performance.

**Comment by fregante** [comment]
> modify the CSS of commit messages based on label

Use the `:has()` selector, like `.listitem:has([rgh-conventional-commits=bug]) {border-color: red}`. You’ll just have to copy the variables yourself and customize them if needed. I’m not a fan of making changes to code (and maintaining it) that one or zero people will take advantage of. 

> worse for performance.

Attribute selectors perform just about the same as class selectors, either way they don’t differ enough to be important. Here the code is just better with attributes. 

> making the chip/badge little bit smaller

Labels on GitHub are 12px, here I set them to 14px, the rest of the line is 16px. I tried both 12px and 16px and I think 14px is the sweet spot.

**Comment by fregante** [comment]
What are your thoughts on using emojis instead of colors to differentiate the various types? This would make the feature less _in your face_ and it would keep the visual style/coolors people are already familiar with.

<table>
<tr>
	<th>Before
	<th>After
<tr>
	<td><img width="295" alt="Screenshot 1" src="https://github.com/user-attachments/assets/8eb90975-667c-4fc4-8321-7d554b97e98f">
	<td><img width="295" alt="Screenshot" src="https://github.com/user-attachments/assets/c4e97436-a4dd-4a51-900b-a2c22048c271">
</table>








Demo CSS
```css
[rgh-conventional-commits] {
    --label-r: 255;
    --label-g: 255;
    --label-b: 255;
    --label-h: 0;
    --label-s: 0;
    --label-l: 100;
}
[rgh-conventional-commits="feat"]:before {content: '✨ '}
[rgh-conventional-commits="fix"]:before {content: '🐛 '}
[rgh-conventional-commits="docs"]:before {content: '📚 '}
[rgh-conventional-commits="style"]:before {content: '💎 '}
[rgh-conventional-commits="refactor"]:before {content: '📦 '}
[rgh-conventional-commits="perf"]:before {content: '🚀 '}
[rgh-conventional-commits="test"]:before {content: '🚨 '}
[rgh-conventional-commits="build"]:before {content: '🛠 '}
[rgh-conventional-commits="ci"]:before {content: '⚙️ '}
[rgh-conventional-commits="chore"]:before {content: '♻️ '}
[rgh-conventional-commits="revert"]:before {content: '🗑 '}
```
