### ISSUE TITLE
Add button to toggle full-page width

### ISSUE THREAD

**Issue by stamminator** [refined-github/refined-github#7827]
### Description

I frequently find myself wanting to use my full browser window's width to display repo content. The limitation on the page content's width improves text readability and is a sensible default, but sometimes it makes reading a file a chore by shrinking down large images, making table columns too narrow, or requiring lots of horizontal scrolling for wide code blocks. Being able to toggle in and out of full-width mode with the push of a button would be very convenient.

I'm currently accomplishing this with some custom CSS, but Refined Github exposing a button to toggle this behavior would be great.

```css
@media screen and (min-width: 1280px) {
  .react-repos-overview-margin {
    margin-right: 0;
  }
}

.repository-content > div:first-of-type,
#repo-content-turbo-frame > div:first-of-type,
#repository-container-header > div,
article.markdown-body {
    max-width: none;
}
```

https://github.com/user-attachments/assets/dc7bcddb-f819-429a-879a-ff71daa48f26

### Example URLs

https://github.com/refined-github/refined-github
