### ISSUE TITLE
Can we hide "Latest changes" section?

### ISSUE THREAD

**Issue by TheBestPessimist** [refined-github/refined-github#7881]
![image](https://github.com/user-attachments/assets/f7f9280e-c00e-4cef-8281-af520d7cbf0a)

**Comment by fregante** [comment]
You only need this in your "Custom CSS" field:


```css
.dashboard-changelog {
	display: none;
}
```
