### ISSUE TITLE
Copilot removal

### ISSUE THREAD

**Issue by GrahamCampbell** [refined-github/refined-github#8004]
### Description

Remove all copilot buttons from the UI, including the explain on actions logs.

### Example URLs

https://github.com/

**Comment by fregante** [comment]
It's annoying to me too, but unfortunately we can't just hide a whole feature that _presumably_ is good/useful.

I was actually thinking about introducing this as an "opt-in" feature just for myself, but ended up just using Safari's "hide distracting elements" feature to hide each button.

If you write a userstyle or uBlock-style selector list, please post it below so it can be useful to others.

**Comment by GrahamCampbell** [comment]
Yeh, I've adblocked it too, but I think it may be useful to have this as part of this, for those who want an easy way to block it, and future additional copilot things.

**Comment by fregante** [comment]
Opt-in features don't belong to Refined GitHub. You can use this snippet for now, feel free to add more selectors below

```css
[partial-name="copilot-code-chat"],
#copilot-chat-header-button,
#copilot-floating-button {
	display: none !important;
}
```

**Comment by cyb3rko** [comment]
To remove the chat on the homepage the following worked for me:

```css
.copilotPreview__container,
[partial-name="copilot-code-chat"],
#copilot-floating-button {
	display: none !important;
}
```
