### ISSUE TITLE
Pink corruption

### ISSUE THREAD

**Issue by viluon** [refined-github/refined-github#8091]
### Description

without hover:
![image](https://github.com/user-attachments/assets/fb7d85a0-9f83-4c47-9e58-4a762a6e2974)
with hover:
![image](https://github.com/user-attachments/assets/11252f34-fedd-4929-aa51-0d8a70ecbb69)

Dev tools show the fuchsia colour, likely a regression due to https://github.com/refined-github/refined-github/pull/8079.

![image](https://github.com/user-attachments/assets/b3b7b4c0-839f-4ced-b49a-154faa977549)

**This is on GHES 3.13.7.**

### How to replicate the issue + URL

Sorry, I can't provide a GHES URL. I could not reproduce this on GitHub.com.

Example: https://github.com/refined-github/refined-github/pull/7785/files

### Extension version

24.11.21

### Browser(s) used

Firefox Developer Edititon 133.0b8 (64-bit)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by viluon** [comment]
On the same GHES server, also see pink corruption in the notifications panel
![image](https://github.com/user-attachments/assets/e2b16642-fa70-41e3-baf2-1cb9f4d1283e)

Again, not reproducible on GitHub.com.

Neither was an issue yesterday, before Refined GitHub update. Clearing the cache doesn't help.

**Comment by fregante** [comment]
Thanks for the report. 

Yes the color is specifically used to highlight broken color variables. In your case, the variable we used aren't yet available. 

Can you check what colors your GitHub instance uses on the native expand-diff button on the left? Only people who know what color variables are available can fix this issue.

**Comment by viluon** [comment]
Thanks for the swift reply. I'm done with work today but I'll check tomorrow morning.

**Comment by nicolasff** [comment]
Hello,

I am seeing this as well on 3.11.15 (extension: 24.11.21), with two parts of the page showing as fuschia.

First, on a PR where we see the author's username and branch name, written as `some-name-here:their-branch-name`. They're wrapped together in a single `<a class="no-underline"> … </a>` and this is always entirely fuschia.

I see the following applied:
```css
:root .rgh-non-default-branch, :root .rgh-non-default-branch a {
    color: var(--control-checked-fgColor-rest, var(--color-state-hover-primary-text, fuchsia));
}
```
Neither of these variables are defined.

And the second fuschia element is on the Files tab of a PR, on the very first or very last line shown of one of the files, usually in pale blue and with a button on the left to load more context before changed lines (I hope this makes sense). This happens only when the cursor goes over this element, the entire pale blue bar changes to fuschia. Here's a screenshot taken on GitHub.com just to show what elements I'm referring to:

![Screenshot 2024-11-21 at 14 21 20](https://github.com/user-attachments/assets/689d70f1-b237-4885-99f3-38ef512c73de)

For this second case, I see the following applied:
```css
.rgh-extend-diff-expander .js-expandable-line:hover :is(.blob-num:not(:hover) .directional-expander:first-child, .blob-num:not(:hover) + .blob-code) {
    color: var(--control-checked-fgColor-rest, var(--color-state-hover-primary-text, fuchsia));
    cursor: pointer;
    background: var(--control-checked-bgColor-hover, var(--color-state-hover-primary-bg, fuchsia));
    border-color: var(--control-checked-borderColor-hover, var(--color-state-hover-primary-border, fuchsia));
}
```
Here also none of these variables have known values, I see them all reported as undefined (notice how the variable names are displayed in gray, I believe that's what it means):

<div align=center>
<img width="486" alt="image" src="https://github.com/user-attachments/assets/63343779-facc-4886-989d-1f7f24a216a4">
</div>

This was on a `<td>` with the class `blob-code blob-code-inner blob-code-hunk rgh-linkified-code`.

I hope this helps!
