### ISSUE TITLE
Full width gists

### ISSUE THREAD

**Issue by mwisnicki** [refined-github/refined-github#8150]
### Description

Something like this to make gist content wider

```css
#gist-pjax-container .container-lg {
	max-width: none;
}
```

### Example URLs

https://gist.github.com/
