### ISSUE TITLE
`align-issue-labels`: alignment doesn't work for "Issue"

### ISSUE THREAD

**Issue by nazdridoy** [refined-github/refined-github#8256]
### Description

In issue/PR lists, doesn't aligns the labels to the left, below each title.

![Image](https://github.com/user-attachments/assets/655be631-9b32-4d58-b437-cd08b06d1d59)

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

### Extension version

25.1.24

### Browser(s) used

firefox, zen

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

**Comment by baodrate** [comment]
Kind of hacky fix (it doesn't precisely match the style on the older issues page/current PR page):

```css
[class^="IssueRow"] > [class^="ListItem"] {
    [class*="trailingBadgesContainer"] {
        display: block;
        padding-top: var(--base-size-4);
    }
}
```
