### ISSUE TITLE
Sticky header for issue / PR / discussion comments

### ISSUE THREAD

**Issue by karlhorky** [refined-github/refined-github#8463]
Hi @fregante, hope everything is good with you! 👋

### Description

For long comments on issues, PRs and discussions, I was wondering if there would be any appetite for Refined GitHub to have a sticky header for quick access to common features without scrolling up to the top of the comment (editing the comment, linking to the comment, navigating to the commenter's GitHub profile, anything else in the three dots menu).

It would mean that there would be 2 sticky headers, although the comment header is not very tall.

I would find this personally useful when making many updates to long comments, where I want to visually see the bottom of the comment, but quickly be able to edit the comment.

### Example URLs

- https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741
- https://github.com/nodejs/typescript/issues/14

### Mockup

https://github.com/user-attachments/assets/fdb887c4-9328-4fc9-929c-2a3416936b06

**Comment by fregante** [comment]
I'd accept a small PR for this, separate CSS-only feature. However it needs to handle:

- that bar
- mobile view (should be the same)
- notification bar
- automatically adjust when the notification bar is closed

We have some other feature that handles the notification header height, I think `sticky-sidebar`, so you should be able to piggy-back on its logic or copy-paste its selector.

However it should still only be CSS only and avoid broad `:has()` usage (e.g. `body:has()`)

**Comment by Vangelis66** [comment]
**Browser**: Firefox Nightly v**142.0a1** 32-bit

I've tested the artifact from: 

https://github.com/refined-github/refined-github/actions/runs/16232281217?pr=8544

on below **GH issue**: 

https://github.com/e3kskoy7wqk/Firefox-for-windows-7/issues/69

and there's a bug when I scroll down to **my comment**; e.g. 

https://github.com/e3kskoy7wqk/Firefox-for-windows-7/issues/69#issue-3203311286

is fine: 

<img width="1039" height="450" alt="Image" src="https://github.com/user-attachments/assets/f99433a9-8e2e-48c9-b805-26acfe996ba1" />

... however 

https://github.com/e3kskoy7wqk/Firefox-for-windows-7/issues/69#issuecomment-3040324555

appears bugged (the second fixed header has a **transparent** background) : 

<img width="942" height="262" alt="Image" src="https://github.com/user-attachments/assets/d106974c-25a8-4918-81fc-92fa104b4e90" />

Hopefully an easy fix 😄 ...

**Comment by Vangelis66** [comment]
> Thank you

... You're welcome!

> can you post that **on that PR**? Not on this issue

Sure 😄 : https://github.com/refined-github/refined-github/pull/8544#issuecomment-3065792439

**Comment by fregante** [comment]
@karlhorky maybe in a future where we only have one React view to support and they have acceptable classes, this can be implemented. 

Judging by the verbose selectors in the attempted PR, this feature would be broken in about 9 days and create performance issues in 17 days.

**Comment by fregante** [comment]
Those interested can attempt to copy-paste it @SunsetTechuila's CSS and ride it while it works.

**Comment by karlhorky** [comment]
Ahh too bad :( Well let's hope for that future then.

## Current CSS Solution

I'll try out the Refined GitHub "Custom CSS" feature with my modified version of CSS below (changes: set background to gray to avoid transparency, z-index fixes for videos, fix weird Biome CSS formatting) from @SunsetTechuila's PR #8544 :

- https://github.com/refined-github/refined-github/pull/8544/files#diff-78e683a73e20858e09eb458d59f87f8cf6d4f4c172065e375dbd7beef53815e7

```css
/* https://github.com/refined-github/refined-github/issues/8463#issuecomment-3094626175 */

/* Issue body header */
[class^="IssueBodyHeader-module__IssueBodyHeaderContainer"],
/* Issue comment header */
[data-testid='comment-header'],
/* PR body/comment header */
.timeline-comment-header {
	position: sticky;
	top: calc(var(--base-sticky-header-height, 0px) + 56px);
	z-index: 3;
	background: var(--bgColor-muted, var(--color-canvas-subtle)) !important;
}

[id^="gistcomment"] .timeline-comment-header {
	top: 0;
}

/* Show menus on top of headers */
.js-comment-container:has(details[open]) .timeline-comment-header {
	z-index: 4;
}

[class^="IssueBodyHeader-module__IssueBodyHeaderContainer"],
[data-testid="comment-header"] {
	border-radius: 0;
}

/* Issue body container */
[data-testid="issue-body"] [class^="Box"]:has(> #issue-body-viewer),
/* Issue comment container */
[class^="IssueCommentViewer-module__IssueCommentContent"] {
	border-radius: var(--borderRadius-medium);
	overflow: clip;
}

@supports (anchor-name: --test) {
	[app-name="issues-react"] {
		[class*="ActivityHeader-module__activityHeader"]
			button[aria-haspopup="true"][aria-expanded="true"] {
			anchor-name: --header;
		}

		[class^="prc-Overlay-Overlay"][data-variant="anchored"]:has(
				.octicon-quote,
				[class*="scrollableEditHistoryList"]
			) {
			position: fixed !important;
			position-anchor: --header;
			top: anchor(bottom) !important;
		}
	}
}
```

Also added to my GitHub Tricks repo here: https://github.com/karlhorky/github-tricks#refined-github-sticky-comment-headers

Since I pasted this like 5 minutes ago, it's already delivering value! Already interacted intuitively with the sticky headers like 3 times.

I'll report back to this issue with any problems I encounter over time, including any fixes I make to the CSS. Maybe if we see a longer period of stability (or a change which makes the approach nicer), we can reconsider making this a feature again.

**Comment by fregante** [comment]
`rgh-OFF-sticky-comment-header` doesn't exist so you might want to remove that. Thanks for sharing!

**Comment by karlhorky** [comment]
## Stability updates for [the CSS solution](https://github.com/refined-github/refined-github/issues/8463#issuecomment-3094626175)

- 15 Sep 2025: No visible problems
- 21 Jul 2025: No visible problems

## Testing Methodology for [the CSS solution](https://github.com/refined-github/refined-github/issues/8463#issuecomment-3094626175)

1. Go to issue https://github.com/nodejs/typescript/issues/14 and check for any visual bugs
2. Go to PR https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741 and check for any visual bugs

**Comment by Vangelis66** [comment]
> I'll report back to this issue **with any problems I encounter over time**,

Many thanks @karlhorky for the CSS code snippet shared 👍 ; however, I recently discovered the "feature" it implements is kinda **broken** when inside a **GitHub gist** with (many) comments 😞 : 

https://gist.github.com/bpsib/67089b959e4fa898af69fea59ad74bc3

<img width="916" height="306" alt="Image" src="https://github.com/user-attachments/assets/922ea7b8-4a47-4299-bfb2-e3120ab0b1ab" />

Either support for **Gists** must be removed (but the extension itself _does support_ Gists) or proper **Gists** support instated...

Best regards 😄 !

**Comment by SunsetTechuila** [comment]
```css
[id^="gistcomment"] .timeline-comment-header {
    top: 0;
}
```

**Comment by karlhorky** [comment]
@SunsetTechuila @Vangelis66 thanks! Updated [the Current CSS Solution post](https://github.com/refined-github/refined-github/issues/8463#issuecomment-3094626175) above.

**Comment by SunsetTechuila** [comment]
> set background to gray to avoid transparency,

I think it would be better to hardcode the color if you always use dark theme:

```css
.timeline-comment.current-user .timeline-comment-header,
[class*="IssueBodyHeader-module__viewerDidAuthor"] {
    background: linear-gradient(var(--bgColor-accent-muted)), var(--bgColor-default) !important;
}

[data-testid="comment-header"] {
   --bgColor-accent-muted: rgb(18, 29, 47);
}
```
